--- 
- hosts: all
  become: yes
  tasks:
  - name: webserver
    apt:
     name: "{{my_ubuntu_web_package}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: start the apache service is not stasrtyefg\
    service:
      name: "{{my_redhat_web_package}}"
      state: restarted
    when: ansible_os_family=="Debian"


  - name: webserver on redhat
    yum: 
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
  
  - name: i want to restart the httpd service on redhat
    service: 
     name: httpd
     state: restarted
    when: ansible_os_family=="RedHat"



