---
- hosts: mywevservers 
  become: yes
  tasks:
    - name: install java on ubuntu node
      apt:
        name: "{{java_package_on_ubuntu}}"
        state: present
      when: ansible_os_family== "Debian"

    - name: install java on amazon linux
      yum:
        name: "{{java_package_on_redhat}}"
        state: present
      when: ansible_os_family== "RedHat"