--- 
- hosts: 172.31.12.187
  become: yes
  tasks:
  - name: i want to excute the linux command
    command: uname
    register: saved_result

  - name: display purpose
    debug:
      msg: "{{saved_result}}"