--- 
- hosts: 172.31.12.187
  become: yes
  tasks:
  - name: i want to excute linux commands
    command: hostname -f 
    register: myresult

  - name: display myresult
    debug: 
     msg: "{{myresult}}"

  - name: i want to install git
    apt:
     name: git
     state: present
    when: myresult.stderr!=""

  - name: i want to install tree
    apt:
     name: tree
     state: present
    when: myresult.stderr==""