--- 
- hosts: 172.31.12.187
  become: yes
  tasks: 
  - name: i want to create a file on node side
    file:
      path: /home/ubuntu/bhaskartestfile
      state: touch
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt: 
     name: apache2
     state: present

  - name: i want to copy the index_file to node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html