---
- name: i want to install webserver on ubuntu
  apt: 
     name: apache2
     state: present

- name: copy the index file into node side
  template:
    src: templates/myindex.j2
    dest: /var/www/html/index.html

